== Spring-Boot Camel QuickStart

This example demonstrates how you can use Apache Camel with Spring Boot
based on a https://github.com/fabric8io/base-images#java-base-images['fabric8 Java base image'].

The quickstart uses Spring Boot to configure a little application that includes a Camel
route that triggers a message every 5th second, and routes the message to a log.

The application utilizes the Spring http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/ImportResource.html[`@ImportResource`] annotation to load a Camel Context definition via a _src/main/resources/spring/camel-context.xml_ file on the classpath.

IMPORTANT: This quickstart can run in 2 modes: standalone on your machine and on Kubernetes / OpenShift Cluster

== Deployment options

You can run this quickstart in the following modes:

* Kubernetese / Single-node OpenShift cluster
* Standalone on your machine

The most effective way to run this quickstart is to deploy and run the project on OpenShift.

For more details about running this quickstart on a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://appdev.openshift.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

== Running the Quickstart on a single-node Kubernetes/OpenShift cluster

A single-node Kubernetes/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetes/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.

To deploy this quickstart to a running single-node OpenShift cluster:

. Download the project and extract the archive on your local filesystem.

. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/spring-boot-camel`) :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/spring-boot-camel
----

. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests fabric8:deploy -Popenshift
----

. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pod for the `spring-boot-camel` has started up.

. On the project's `Overview` page, navigate to the details page deployment of the `spring-boot-camel` application: `https://OPENSHIFT_IP_ADDR:8443/console/project/MY_PROJECT_NAME/browse/rc/spring-boot-camel-NUMBER_OF_DEPLOYMENT?tab=details`.

. Switch to tab `Logs` and then see the messages sent by Camel.

== Running the quickstart standalone on your machine

To run this quickstart as a standalone project on your local machine:

. Download the project and extract the archive on your local filesystem.
. Build the project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd PROJECT_DIR
$ mvn clean package
----
. Run the service:

+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn spring-boot:run
----
. See the messages sent by Camel.

== Integration Testing

The example includes a https://github.com/fabric8io/fabric8/tree/master/components/fabric8-arquillian[fabric8 arquillian] Kubernetes Integration Test.
Once the container image has been built and deployed in Kubernetes, the integration test can be run with:

[source,bash,options="nowrap",subs="attributes+"]
----
mvn test -Dtest=*KT
----

The test is disabled by default and has to be enabled using `-Dtest`. https://fabric8.io/guide/testing.html[Integration Testing] and https://fabric8.io/guide/arquillian.html[Fabric8 Arquillian Extension] provide more information on writing full fledged black box integration tests for Kubernetes.